
---

- name: Enable necessary repos 1
  command: yum-config-manager --enable rhui-REGION-rhel-server-extras rhui-REGION-rhel-server-optional

#Takes too long
#- name: Yum update
#  command: yum update

- name: upgrade all packages
  yum: name=* state=latest

- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/
  
- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Install Git-core
  package: name=git-core state=latest

- name: ensure python-selinux is installed on all nodes.
  action: yum name=libselinux-python state=installed  

- name: install firewalld 
  yum: name=firewalld state=present

- name: ensure that firewalld is started and enable at boot
  service: name=firewalld enabled=yes state=started

- name: set SELinux to enforcing
  action: selinux policy=targeted state=enforcing
  register: st

- name: reboot if SELinux changed
  shell: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true
  when: st.changed

- name: waiting for server to reboot
  wait_for: host="{{ ansible_ssh_host | default(inventory_hostname) }}" port={{ ansible_ssh_port | default(22) }} search_regex=OpenSSH delay=30 timeout=120
  connection: local
  sudo: false
  when: st.changed